version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data

  influxdb:
    image: influxdb:2.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_data:/etc/influxdb2

<<<<<<< HEAD
  grafana:
    image: grafana/grafana-oss:10.4.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin           # Change this for production!
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

=======
>>>>>>> 0b250a89384a8f499ca50ad5a402b71789d850cc
  room-subscriber:
    build: .
    env_file:
      - .env
    depends_on:
      - mosquitto
      - influxdb
<<<<<<< HEAD
      - grafana
=======
>>>>>>> 0b250a89384a8f499ca50ad5a402b71789d850cc
    restart: unless-stopped

volumes:
  mosquitto_data:
  influxdb_data:
<<<<<<< HEAD
  grafana_data:
=======
>>>>>>> 0b250a89384a8f499ca50ad5a402b71789d850cc
